services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    environment:
      VITE_BACKEND_API_URL: http://backend:3003
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3003:3000"
    environment:
      OPENROUTER_API_URL: https://openrouter.ai/api/v1/chat/completions
      OPENROUTER_API_KEY: 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
      MONGO-URI: mongodb://mongodb:27017
      PORT: 3003
      CLIENT_API_URL: http://client:5173
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
