name: Client CI

on:
  push:
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"

env:
  NETLIFY_SITE_ID: c1e48986-8667-47c1-8d57-f3116cd37027
  NETLIFY_AUTH_TOKEN: nfp_FqSavsmDuF7XQtQAFCtRpCdTmKSJXDYK927e

jobs:
  client-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/dist

  client-unit-testing:
    runs-on: ubuntu-latest
    needs: client-build
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Unit Tests
        run: npm run test:unit

  client-e2e-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests
        run: npx playwright test

  client-deploy-staging:
    runs-on: ubuntu-latest
    needs: client-build
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project (if not using artifact)
        run: npm run build

      - name: Install Netlify CLI and node-jq
        run: |
          npm install netlify-cli node-jq
          ./node_modules/.bin/netlify --version

      - name: Deploy to Netlify (Staging)
        run: |
          echo "Deploying to Netlify Staging. Site ID: $NETLIFY_SITE_ID"
          ./node_modules/.bin/netlify status
          ./node_modules/.bin/netlify deploy --dir=dist --json > deploy-output.json
          ./node_modules/.bin/node-jq -r '.deploy_url' deploy-output.json

      - name: Export Staging URL
        id: deploy
        run: echo "STAGING_URL=$(./node_modules/.bin/node-jq -r '.deploy_url' deploy-output.json)" >> $GITHUB_OUTPUT
