name: Client CI

on:
  push:
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"

env:
  NETLIFY_SITE_ID: c1e48986-8667-47c1-8d57-f3116cd37027

jobs:
  client-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/dist

  client-unit-testing:
    runs-on: ubuntu-latest
    needs: client-build
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Unit Tests
        run: npm run test:unit

  client-e2e-testing:
    runs-on: ubuntu-latest
    needs: client-build
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests
        run: npx playwright test

  client-deploy-staging:
    runs-on: ubuntu-latest
    needs: [client-unit-testing, client-e2e-testing]
    defaults:
      run:
        working-directory: client
    outputs:
      staging_url: ${{ steps.deploy.outputs.STAGING_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: client-build
          path: client/dist

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Netlify CLI and node-jq locally
        run: npm install netlify-cli node-jq --legacy-peer-deps

      - name: Check build output
        run: ls -la dist

      - name: Deploy to Netlify (Staging)
        id: deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}
        run: |
          echo "Deploying to Netlify Staging. Site ID: $NETLIFY_SITE_ID"
          ./node_modules/.bin/netlify status
          ./node_modules/.bin/netlify deploy --dir=dist --json > deploy-output.json
          echo "STAGING_URL=$(./node_modules/.bin/node-jq -r '.deploy_url' deploy-output.json)" >> $GITHUB_OUTPUT

  staging-e2e-testing:
    runs-on: ubuntu-latest
    needs: client-deploy-staging
    defaults:
      run:
        working-directory: client

    env:
      DEPLOY_URL: ${{ needs.client-deploy-staging.outputs.staging_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Staging E2E Tests
        run: |
          echo "Running E2E tests against: $DEPLOY_URL"
          npx playwright test
