name: E2E Cycle

on:
  push:
    paths:
      - "client/**"
      - "backend/**"
  pull_request:
    paths:
      - "client/**"
      - "backend/**"

jobs:
  run-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/dist

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: client-build
          path: client/dist

      - name: Install serve
        run: npm install serve --legacy-peer-deps

      - name: Serve app and run Playwright tests
        run: |
          npx serve -s dist -l 5173 &
          npx wait-on http://localhost:5173
          npx playwright test

  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Tests
        run: npm test
